### PR TITLE
Add Socratic 31

### PR DESCRIPTION
**Pull request by stickies-v**
Topics and links can be pushed directly to this branch, or added as comments/review.

### CODE REVIEW

**Comment by ariard** [comment]
ledger hack + ordinals:
https://github.com/ariard/londonbitdevs-website/commit/cba6e97f7e18667c2086afb68bc7f8db5ece5062

**Comment by ariard** [comment]
pushed, the ledger hack is worthy to go deep into like we done for milksad. a lot of interesting things.

**Comment by stickies-v** [comment]
It seems like you've force-pushed all of my commits out, fixed it now by rebasing yours on top

**Comment by ariard** [comment]
ah sorry.

**Comment by glozow** [comment]
Added delving links. I didn't look at PRs as it looks like there's plenty already.

**Comment by stickies-v** [comment]
Cleaned up the post, RFM

**Pull request merged**
