### PR TITLE
Add Socratic 30

### PR DESCRIPTION
**Pull request by stickies-v**
Topics and links can be pushed directly to this branch, or added as comments/review.

### CODE REVIEW

**Comment by ariard** [comment]
Thinking to do something on:
- the codex32 scheme: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-February/021469.html / https://blog.blockstream.com/codex32-a-shamir-secret-sharing-scheme/
-  the “purely off-chain coin coloring” discussion on trade-offs: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-November/022176.html
- the renumbering debate in ordinals https://rodarmor.com/blog/the-stable-is-the-aesthetic/

(Presenting the codex32 scheme for the first time might be bandwidth-consuming so I might only do this subject for socratic 30)

**Comment by stickies-v** [comment]
Added the recurring stuff. Not too much happening this month on ML and Bitcoin Core pulls (that aren't refactoring/purely internal)

> Presenting the codex32 scheme for the first time might be bandwidth-consuming so I might only do this subject for socratic 30

Normally I'd say I prefer covering topics that surfaced in the previous month, but given that it's been a bit of a quiet month that could be a good topic to cover now. Feel free to push the commit to this branch.

**Comment by ariard** [comment]
Here you go: https://github.com/ariard/londonbitdevs-website/commit/d5d7ab0b005e2e4fc9d37d5eee0d58027bae4106

> Normally I'd say I prefer covering topics that surfaced in the previous month, but given that it's been a bit of a quiet month that could be a good topic to cover now. Feel free to push the commit to this branch

Yep, those topics surfaced in September actually, and October edition we spend a lot on mempool as usual.

**Comment by stickies-v** [comment]
> Here you go: [ariard@d5d7ab0](https://github.com/ariard/londonbitdevs-website/commit/d5d7ab0b005e2e4fc9d37d5eee0d58027bae4106)
> 
> >

Thanks, could you push directly to [stickies-v/londonbitdevs-website](https://github.com/stickies-v/londonbitdevs-website). please? You have write access.

**Comment by glozow** [comment]
Added my links and ariard's. Lmk if anybody wants to add anything else, I'll be doing a quick runthrough and then merge.

A TODO is to add delving bitcoin to the template / places we scrape - I don't have time to do that today.

**Pull request merged**
