### PR TITLE
Add Socratic 27

### PR DESCRIPTION
**Pull request by stickies-v**
Topics and links can be pushed directly to this branch, or added as comments/review.

### CODE REVIEW

**Comment by glozow** [comment]
Thanks @stickies-v

**Comment by ariard** [comment]
Adding the “waiting for confirmation” serie as a nugget to dig during next bitdev: https://bitcoinops.org/en/blog/waiting-for-confirmation/

**Comment by ariard** [comment]
+1 on milk sad and happy to talk about https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-August/004064.html if we have time with the “waiting for confirmation serie” :)

**Comment by ariard** [comment]
Here the mention of the concrete matt opcode mailing list post: https://github.com/ariard/londonbitdevs-website/commit/9dd1c417d34fe0d76a9632d6a9b146da71045e1f and I’m all good on my side.

**Comment by stickies-v** [comment]
@glozow I think we're RFM.

**Comment by glozow** [comment]
Good stuff. Thanks @ariard @stickies-v, looking forward to it! :rocket:

**Pull request merged**
