### PR TITLE
Add Socratic 29

### PR DESCRIPTION
**Pull request by stickies-v**
Topics and links can be pushed directly to this branch, or added as comments/review.

### CODE REVIEW

**Comment by ariard** [comment]
cool to explore new things, links on bitvm and runes the new ordinals thing on my side: https://github.com/ariard/londonbitdevs-website/commit/befb45669fdc5e8a81b200b8e67bce1c677b17b6

**Comment by stickies-v** [comment]
Thanks @ariard, cherry-picked your commit. FYI I've given you write access on this repo so could add it as a remote.

**Comment by glozow** [comment]
I was doing redundant work :facepalm: just a few additions

**Comment by stickies-v** [comment]
Cleaned up, RFM @glozow

**Comment by glozow** [comment]
I added links to the bips repo and reorganized the commits. Merging now.

**Pull request merged**
